/**
 * Catalog data — pure reference data for species profiles, medicinal
 * properties, bioactive compounds and cultivation recipes.
 *
 * ADR (I68): catalog data is separated from development fixtures so it
 * can be seeded independently of test users/chambers and without
 * injecting fake credentials. This module MUST be side-effect free:
 * no database imports, no env access.
 */

export const DIFFICULTY_MAP = {
  'Principiante': 'BEGINNER',
  'Intermedio': 'INTERMEDIATE',
  'Avanzado': 'ADVANCED',
};

export const SPECIES = [
  {
    id: 'hericium-erinaceus',
    nombre_comun: 'Melena de León',
    nombre_cientifico: 'Hericium erinaceus',
    clase: 'Medicinal',
    dificultad: 'Intermedio',
    clima_origen: 'Templado',
    descripcion: 'Hongo con aspecto de cascada de espinas blancas. Altamente valorado por sus propiedades nootrópicas y de salud neurológica.',
    propiedades_medicinales: [
      { categoria: 'Nootrópico y Cognitivo', descripcion: 'Estimula la síntesis de NGF (Factor de Crecimiento Nervioso), mejorando la memoria y concentración.' },
      { categoria: 'Gastroprotector', descripcion: 'Apoya la salud de la mucosa gástrica y la microbiota intestinal.' },
    ],
    compuestos_bioactivos: [
      { nombre: 'hericenones', valor: null },
      { nombre: 'erinacines', valor: null },
      { nombre: 'beta Glucans', valor: '30%' },
    ],
    atributos_generales: {
      ciclo_estimado_semanas: '8-10',
      eficiencia_biologica_promedio: '60-80%',
      sustratos_compatibles: ['Serrín de maderas duras', 'Suplemento de salvado de trigo'],
    },
  },
  {
    id: 'ganoderma-lucidum',
    nombre_comun: 'Reishi',
    nombre_cientifico: 'Ganoderma lucidum',
    clase: 'Medicinal',
    dificultad: 'Avanzado',
    clima_origen: 'Subtropical',
    descripcion: "El 'hongo de la inmortalidad'. Rico en triterpenos y betaglucanos. Forma de estante y consistencia leñosa.",
    propiedades_medicinales: [
      { categoria: 'Inmunomodulador', descripcion: 'Estimula la respuesta del sistema inmunitario y combate la fatiga.' },
      { categoria: 'Adaptógeno y Relajante', descripcion: 'Ayuda a reducir el estrés físico/mental y promueve la calidad del sueño.' },
      { categoria: 'Hepatoprotector', descripcion: 'Apoya la función hepática y reduce la inflamación celular.' },
    ],
    compuestos_bioactivos: [
      { nombre: 'beta Glucans', valor: '40%' },
      { nombre: 'triterpenes', valor: null },
      { nombre: 'ganodermanontriol', valor: null },
    ],
    atributos_generales: {
      ciclo_estimado_semanas: '12-16',
      eficiencia_biologica_promedio: '50-80%',
      sustratos_compatibles: ['Serrín de maderas duras', 'Paja de trigo', 'Afrecho de trigo'],
    },
  },
  {
    id: 'lentinula-edodes',
    nombre_comun: 'Shiitake',
    nombre_cientifico: 'Lentinula edodes',
    clase: 'Comestible / Medicinal',
    dificultad: 'Intermedio',
    clima_origen: 'Templado húmedo',
    descripcion: 'Clásico hongo asiático de sombrero marrón oscuro, gran sabor umami y excelentes propiedades inmunitarias.',
    propiedades_medicinales: [
      { categoria: 'Inmunoestimulante', descripcion: 'Contiene lentinan, conocido por potenciar las defensas del organismo.' },
      { categoria: 'Cardiovascular', descripcion: 'Ayuda a mantener niveles saludables de colesterol gracias al eritadenine.' },
    ],
    compuestos_bioactivos: [
      { nombre: 'lentinan', valor: null },
      { nombre: 'eritadenine', valor: null },
      { nombre: 'beta Glucans', valor: '25%' },
    ],
    atributos_generales: {
      ciclo_estimado_semanas: '10-14',
      eficiencia_biologica_promedio: '75-100%',
      sustratos_compatibles: ['Serrín de roble / maderas duras', 'Tarugos de madera (cultivo en troncos)'],
    },
  },
  {
    id: 'trametes-versicolor',
    nombre_comun: 'Cola de Pavo',
    nombre_cientifico: 'Trametes versicolor',
    clase: 'Medicinal',
    dificultad: 'Principiante',
    clima_origen: 'Templado',
    descripcion: 'Hongo medicinal con forma de abanico y anillos coloridos. Alto contenido de PSP (polisacárido péptido). Ideal para principiantes por su resistencia.',
    propiedades_medicinales: [
      { categoria: 'Inmunooncología', descripcion: 'Extremadamente estudiado por su apoyo al sistema inmune en terapias integrativas.' },
      { categoria: 'Prebiótico', descripcion: 'Rico en polisacáridos que nutren la flora intestinal beneficiosa.' },
    ],
    compuestos_bioactivos: [
      { nombre: 'P S P', valor: null },
      { nombre: 'beta Glucans', valor: '35%' },
      { nombre: 'polysaccharopeptide', valor: null },
    ],
    atributos_generales: {
      ciclo_estimado_semanas: '6-8',
      eficiencia_biologica_promedio: '80-110%',
      sustratos_compatibles: ['Serrín de madera', 'Ramas y troncos caídos'],
    },
  },
  {
    id: 'cordyceps-militaris',
    nombre_comun: 'Cordyceps Militaris',
    nombre_cientifico: 'Cordyceps militaris',
    clase: 'Medicinal',
    dificultad: 'Avanzado',
    clima_origen: 'Templado / Alpino',
    descripcion: 'Hongo entomopatógeno de llamativo color naranja brillante. Potente estimulante de la energía celular y la oxigenación.',
    propiedades_medicinales: [
      { categoria: 'Energético y Rendimiento', descripcion: 'Optimiza la producción de ATP y mejora la utilización de oxígeno durante el ejercicio.' },
      { categoria: 'Antienvejecimiento', descripcion: 'Alto contenido de antioxidantes y cordicepina con efectos revitalizantes.' },
    ],
    compuestos_bioactivos: [
      { nombre: 'cordycepin', valor: null },
      { nombre: 'adenosine', valor: null },
      { nombre: 'beta Glucans', valor: '20%' },
    ],
    atributos_generales: {
      ciclo_estimado_semanas: '6-8',
      eficiencia_biologica_promedio: '40-60%',
      sustratos_compatibles: ['Arroz integral enriquecido', 'Medios líquidos especializados'],
    },
  },
  {
    id: 'pleurotus-ostreatus',
    nombre_comun: 'Pleurotus',
    nombre_cientifico: 'Pleurotus ostreatus',
    clase: 'Comestible',
    dificultad: 'Principiante',
    clima_origen: 'Templado húmedo',
    descripcion: 'Ostra común. Hongo comestible ideal para principiantes. Crecimiento rápido y gran adaptabilidad a diversos sustratos.',
    propiedades_medicinales: [
      { categoria: 'Salud Metabólica', descripcion: 'Contiene compuestos naturales que apoyan la regulación del colesterol.' },
      { categoria: 'Nutricional', descripcion: 'Aporte alto de proteínas vegetales, fibra y antioxidantes.' },
    ],
    compuestos_bioactivos: [
      { nombre: 'beta Glucans', valor: '15%' },
      { nombre: 'lovastatina', valor: null },
      { nombre: 'ergotioneina', valor: null },
    ],
    atributos_generales: {
      ciclo_estimado_semanas: '3-5',
      eficiencia_biologica_promedio: '80-120%',
      sustratos_compatibles: ['Paja de trigo o arroz', 'Serrín de maderas blandas', 'Pulpa de café'],
    },
  },
  {
    id: 'inonotus-obliquus',
    nombre_comun: 'Chaga',
    nombre_cientifico: 'Inonotus obliquus',
    clase: 'Medicinal',
    dificultad: 'Avanzado',
    clima_origen: 'Boreal frío',
    descripcion: 'Hongo parásito de abedules. Altísimo contenido de antioxidantes. Extracción compleja debido a su ciclo de vida silvestre.',
    propiedades_medicinales: [
      { categoria: 'Antioxidante Extremo', descripcion: 'Posee uno de los valores ORAC más altos del reino fúngico, combatiendo el estrés oxidativo celular.' },
      { categoria: 'Antiinflamatorio', descripcion: 'Apoya la respuesta inflamatoria sistémica y la salud de la piel.' },
    ],
    compuestos_bioactivos: [
      { nombre: 'melanina', valor: null },
      { nombre: 'beta Glucans', valor: '45%' },
      { nombre: 'superoxido Dismutasa', valor: null },
    ],
    atributos_generales: {
      ciclo_estimado_semanas: 'Silvestre / No cultivable masivamente en interior a corto plazo',
      eficiencia_biologica_promedio: 'N/D',
      sustratos_compatibles: ['Troncos vivos de abedul'],
    },
  },
];

export const RECIPES = [
  {
    name: 'Pearl Oyster — Standard',
    species: 'Pleurotus ostreatus',
    incubationTempMin: 20, incubationTempMax: 24,
    incubationHumMin: 85, incubationHumMax: 95,
    incubationCo2Max: 1200, incubationDurationDays: 21,
    fruitingTempMin: 14, fruitingTempMax: 18,
    fruitingHumMin: 85, fruitingHumMax: 92,
    fruitingCo2Max: 1000, fruitingDurationDays: 14,
    maintenanceTempMin: 12, maintenanceTempMax: 20,
    maintenanceHumMin: 80, maintenanceHumMax: 90,
    maintenanceCo2Max: 1200,
    faeIntervalMinutes: 10, ventilationStrategy: 'TIMER',
    lightCycleHours: 0, faeLevel: 'MEDIUM', dewPointMaxRH: 90,
  },
  {
    name: 'Pink Oyster — Tropical',
    species: 'Pleurotus djamor',
    incubationTempMin: 24, incubationTempMax: 28,
    incubationHumMin: 85, incubationHumMax: 95,
    incubationCo2Max: 1200, incubationDurationDays: 14,
    fruitingTempMin: 22, fruitingTempMax: 28,
    fruitingHumMin: 88, fruitingHumMax: 95,
    fruitingCo2Max: 1000, fruitingDurationDays: 10,
    maintenanceTempMin: 20, maintenanceTempMax: 26,
    maintenanceHumMin: 85, maintenanceHumMax: 92,
    maintenanceCo2Max: 1200,
    faeIntervalMinutes: 8, ventilationStrategy: 'TIMER',
    lightCycleHours: 0, faeLevel: 'MEDIUM', dewPointMaxRH: 92,
  },
  {
    name: 'Shiitake — Hardwood Log Block',
    species: 'Lentinula edodes',
    incubationTempMin: 21, incubationTempMax: 25,
    incubationHumMin: 80, incubationHumMax: 90,
    incubationCo2Max: 1200, incubationDurationDays: 60,
    fruitingTempMin: 10, fruitingTempMax: 16,
    fruitingHumMin: 80, fruitingHumMax: 88,
    fruitingCo2Max: 900, fruitingDurationDays: 21,
    maintenanceTempMin: 8, maintenanceTempMax: 18,
    maintenanceHumMin: 75, maintenanceHumMax: 85,
    maintenanceCo2Max: 1000,
    faeIntervalMinutes: 15, ventilationStrategy: 'HYBRID',
    lightCycleHours: 10, faeLevel: 'HIGH', dewPointMaxRH: 88,
  },
  {
    name: "Lion's Mane — Low CO2 Profile",
    species: 'Hericium erinaceus',
    incubationTempMin: 22, incubationTempMax: 26,
    incubationHumMin: 85, incubationHumMax: 92,
    incubationCo2Max: 1200, incubationDurationDays: 18,
    fruitingTempMin: 18, fruitingTempMax: 22,
    fruitingHumMin: 85, fruitingHumMax: 92,
    fruitingCo2Max: 800, fruitingDurationDays: 10,
    maintenanceTempMin: 15, maintenanceTempMax: 20,
    maintenanceHumMin: 80, maintenanceHumMax: 90,
    maintenanceCo2Max: 1000,
    faeIntervalMinutes: 6, ventilationStrategy: 'HYBRID',
    lightCycleHours: 6, faeLevel: 'HIGH', dewPointMaxRH: 90,
  },
  {
    name: 'Reishi — Cap/Shelf Form',
    species: 'Ganoderma lucidum',
    incubationTempMin: 24, incubationTempMax: 28,
    incubationHumMin: 85, incubationHumMax: 92,
    incubationCo2Max: 1200, incubationDurationDays: 45,
    fruitingTempMin: 22, fruitingTempMax: 26,
    fruitingHumMin: 85, fruitingHumMax: 90,
    fruitingCo2Max: 700, fruitingDurationDays: 30,
    maintenanceTempMin: 20, maintenanceTempMax: 24,
    maintenanceHumMin: 80, maintenanceHumMax: 88,
    maintenanceCo2Max: 1000,
    faeIntervalMinutes: 12, ventilationStrategy: 'CO2_TRIGGER',
    lightCycleHours: 12, faeLevel: 'HIGH', dewPointMaxRH: 88,
  },
  {
    name: 'Cordyceps militaris — Grain Stroma',
    species: 'Cordyceps militaris',
    incubationTempMin: 20, incubationTempMax: 23,
    incubationHumMin: 80, incubationHumMax: 88,
    incubationCo2Max: 1200, incubationDurationDays: 14,
    fruitingTempMin: 18, fruitingTempMax: 22,
    fruitingHumMin: 80, fruitingHumMax: 88,
    fruitingCo2Max: 1200, fruitingDurationDays: 21,
    maintenanceTempMin: 16, maintenanceTempMax: 20,
    maintenanceHumMin: 75, maintenanceHumMax: 85,
    maintenanceCo2Max: 1500,
    faeIntervalMinutes: 20, ventilationStrategy: 'TIMER',
    lightCycleHours: 12, faeLevel: 'LOW', dewPointMaxRH: 85,
  },
  {
    name: 'Turkey Tail — Extraction Grade',
    species: 'Trametes versicolor',
    incubationTempMin: 20, incubationTempMax: 24,
    incubationHumMin: 80, incubationHumMax: 90,
    incubationCo2Max: 1200, incubationDurationDays: 30,
    fruitingTempMin: 16, fruitingTempMax: 20,
    fruitingHumMin: 80, fruitingHumMax: 88,
    fruitingCo2Max: 950, fruitingDurationDays: 21,
    maintenanceTempMin: 14, maintenanceTempMax: 18,
    maintenanceHumMin: 75, maintenanceHumMax: 85,
    maintenanceCo2Max: 1000,
    faeIntervalMinutes: 15, ventilationStrategy: 'HYBRID',
    lightCycleHours: 8, faeLevel: 'MEDIUM', dewPointMaxRH: 87,
  },
];
