; PlatformIO Project Configuration File
[platformio]
description = Mush2 — Firmware para control de ambientes de hongos adaptógenos
src_dir = src
lib_dir = lib

[env:d1]
platform = espressif8266
board = d1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dout

lib_deps =
    pubsubclient@^2.8
    arduinojson@^7.0
    dfrobot_ens160@^1.0.0

build_flags =
    -Wall
    -Werror=return-type
    -DLED_BUILTIN=2
