[platformio]
description = Mush2 — Firmware para control de ambientes de hongos adaptógenos (ESP32-S3)
src_dir = src
lib_dir = lib

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB

build_flags =
    -Wall
    -Werror=return-type
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BT_BLE_ENABLED=1
    -DCONFIG_BT_NIMBLE_ENABLED=1
    -DFIRMWARE_VERSION="\"0.21.0\""

lib_deps =
    arduinojson@^7.0
    dfrobot_ens160@^1.0.0
    adafruit/Adafruit NeoPixel@^1.12.0
    knolleary/PubSubClient @ ^2.6

[env:esp32-s3-devkitc-1-ota]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = qio
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB
build_flags =
    -Wall
    -Werror=return-type
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BT_BLE_ENABLED=1
    -DCONFIG_BT_NIMBLE_ENABLED=1
    -DFIRMWARE_VERSION="\"0.21.0\""
lib_deps =
    arduinojson@^7.0
    dfrobot_ens160@^1.0.0
    adafruit/Adafruit NeoPixel@^1.12.0
    knolleary/PubSubClient @ ^2.6
upload_protocol = espota
upload_port = 192.168.1.24
upload_flags =
    --auth=mush2ota

